# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:15
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import pgcrypto.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
            ],
            options={
                'permissions': (('view_application', 'Can view application'), ('execute_application', 'Can execute tasks on application')),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
            ],
            options={
                'permissions': (('view_department', 'Can view department'), ('execute_department', 'Can execute department')),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('is_production', models.BooleanField(default=False)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='core.Application')),
            ],
            options={
                'permissions': (('view_environment', 'Can view environment'), ('execute_environment', 'Can execute tasks on environment')),
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('host', models.CharField(max_length=128)),
                ('port', models.IntegerField(default=22)),
                ('user', models.CharField(max_length=128)),
                ('method', models.IntegerField(choices=[(2, 'SSH certificate'), (1, 'SSH password')], default=2, verbose_name='Login method')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ServerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serverroles', to='core.Department')),
            ],
        ),
        migrations.CreateModel(
            name='ServerAuthentication',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Server')),
                ('password', pgcrypto.fields.EncryptedTextField(blank=True, charset='utf-8', check_armor=True, cipher='AES', versioned=False)),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='core.Environment'),
        ),
        migrations.AddField(
            model_name='server',
            name='roles',
            field=models.ManyToManyField(related_name='servers', to='core.ServerRole'),
        ),
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.Department'),
        ),
        migrations.AlterUniqueTogether(
            name='serverrole',
            unique_together=set([('department', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='server',
            unique_together=set([('environment', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='environment',
            unique_together=set([('application', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='application',
            unique_together=set([('department', 'name')]),
        ),
    ]
