# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 23:15
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import task.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Execution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(3, 'pending'), (0, 'running'), (1, 'success'), (2, 'failed'), (4, 'aborted')], default=3)),
                ('celery_task_id', models.CharField(blank=True, max_length=36)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='core.Environment')),
            ],
            bases=(models.Model, task.models.StateMixin),
        ),
        migrations.CreateModel(
            name='ExecutionCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('order', models.IntegerField()),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='task.Execution')),
                ('roles', models.ManyToManyField(to='core.ServerRole')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionCommandServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(3, 'pending'), (0, 'running'), (1, 'success'), (2, 'failed')], default=3)),
                ('time_start', models.DateTimeField(blank=True, null=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('return_code', models.IntegerField(blank=True, null=True)),
                ('output', models.TextField(blank=True)),
                ('celery_task_id', models.CharField(blank=True, max_length=36)),
                ('execution_command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='task.ExecutionCommand')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Server')),
            ],
            options={
                'ordering': ['server__name'],
            },
            bases=(models.Model, task.models.StateMixin),
        ),
        migrations.CreateModel(
            name='ExecutionLiveLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=128)),
                ('data', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_logs', to='task.Execution')),
            ],
        ),
        migrations.CreateModel(
            name='ExecutionParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('value', models.CharField(max_length=128)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='task.Execution')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('description', models.TextField(blank=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.Application')),
            ],
            options={
                'permissions': (('view_task', 'Can view task'), ('execute_task', 'Can execute task')),
            },
        ),
        migrations.CreateModel(
            name='TaskCommand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('order', models.IntegerField()),
                ('roles', models.ManyToManyField(related_name='commands', to='core.ServerRole')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='task.Task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TaskParameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, validators=[django.core.validators.RegexValidator(message='Invalid characters', regex='^[a-zA-Z0-9_\\.\\-]+$')])),
                ('default_value', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField()),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='task.Task')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='execution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='task.Task'),
        ),
        migrations.AddField(
            model_name='execution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set([('application', 'name')]),
        ),
    ]
